const keywords = [
    'nature', 'outdoors', 'outside', 'fresh', 'air', 'sunshine', 'sun', 'sky', 'clouds', 'weather',
    'greenery', 'trees', 'plants', 'grass', 'flowers', 'blossoms', 'leaves', 'foliage', 'shrubs',
    'woods', 'forest', 'woods', 'jungle', 'grove', 'copse', 'thicket', 'clearing', 'wilds', 'woodsman',
    'hiking', 'walk', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hike', 'climb', 'walkabout',
    'camping', 'tenting', 'camp', 'bivouac', 'sleeping', 'picnics', 'lunch', 'snack', 'meal', 'outings',
    'biking', 'cycling', 'bicycle', 'ride', 'ride', 'cycle', 'pedal', 'wheel', 'ride', 'ride',
    'fishing', 'angling', 'fish', 'catch', 'angling', 'fisherman', 'fisherwoman', 'angling', 'angling', 'angling',
    'birdwatching', 'birding', 'birds', 'watch', 'watcher', 'watcher', 'watch', 'watch', 'watch',
    'swimming', 'swim', 'dip', 'dive', 'plunge', 'bathe', 'bathing', 'bath', 'bath', 'bath',
    'beach', 'shore', 'coast', 'sand', 'seashore', 'seaside', 'shoreline', 'seashell', 'tide', 'tidal',
    'lakes', 'lake', 'pond', 'water', 'reservoir', 'lagoon', 'loch', 'laguna', 'bay', 'cove',
    'rivers', 'river', 'stream', 'creek', 'brook', 'channel', 'waterway', 'flow', 'current', 'freshet',
    'mountains', 'mountain', 'peak', 'summit', 'hill', 'ridge', 'mount', 'mountaineer', 'alpine', 'alps',
    'waterfalls', 'waterfall', 'cascade', 'falls', 'cataract', 'plunge', 'plunge', 'rapids', 'rapids', 'rapids',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'relaxation', 'relax', 'unwind', 'unwind', 'chill', 'de-stress', 'rest', 'recharge', 'rejuvenate', 'restoration',
    'outdoor', 'relaxing', 'nature', 'relaxation', 'outdoor', 'leisure', 'fresh', 'air', 'outdoor', 'activity', 'peace',
    'peaceful', 'serene', 'tranquil', 'calm', 'quiet', 'quiet', 'still', 'undisturbed', 'restful', 'placid',
    'campfire', 'camp', 'fire', 'blaze', 'flame', 'embers', 'heat', 'warmth', 'cozy', 'warm',
    'outdoor', 'cooking', 'food', 'cook', 'meal', 'meal', 'lunch', 'picnic', 'barbecue', 'grill',
    'outdoor', 'play', 'fun', 'games', 'sport', 'recreation', 'leisure', 'activity', 'pastime', 'pursuit',
    'fresh', 'nature', 'fresh', 'air', 'fresh', 'greenery', 'fresh', 'breeze', 'fresh', 'scenery', 'fresh',
    'beauty', 'nature', 'beauty', 'outdoors', 'beauty', 'scenery', 'beauty', 'landscapes', 'beauty', 'views', 'beauty',
    'sunshine', 'sun', 'sunny', 'day', 'sunny', 'weather', 'sunshine', 'sky', 'blue', 'sky', 'sky', 'clouds',
    'relaxation', 'relax', 'unwind', 'unwind', 'chill', 'de-stress', 'rest', 'recharge', 'rejuvenate', 'restoration',
    'recreation', 'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment',
    'exercise', 'activity', 'fitness', 'physical', 'activity', 'exercise', 'training', 'workout', 'physical', 'fitness', 'health',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'nature', 'wildlife', 'habitat', 'wildlife', 'preserves', 'wildlife', 'refuge', 'wildlife',
    'expedition', 'safari', 'wildlife', 'photography', 'birdwatching', 'birding', 'bird', 'watching', 'bird', 'photography', 'bird',
    'nature', 'watching', 'bird', 'spotting', 'bird', 'observation', 'bird', 'survey', 'bird', 'study', 'bird', 'counting',
    'water', 'activities', 'water', 'sports', 'water', 'fun', 'water', 'recreation', 'water', 'play', 'water', 'sport',
    'swimming', 'swim', 'dive', 'dip', 'plunge', 'bathing', 'bath', 'bathe', 'soak', 'wading', 'splash',
    'boating', 'boat', 'sail', 'sailing', 'canoeing', 'canoe', 'paddle', 'paddling', 'kayaking', 'kayak', 'rafting',
    'fishing', 'fish', 'angling', 'catch', 'angling', 'angling', 'angling', 'angling', 'angling', 'angling',
    'beach', 'seaside', 'seashore', 'coast', 'shore', 'sandy', 'beach', 'sandy', 'shore', 'sand', 'beach',
    'lakes', 'lake', 'pond', 'water', 'reservoir', 'lagoon', 'loch', 'laguna', 'bay', 'cove',
    'rivers', 'river', 'stream', 'creek', 'brook', 'channel', 'waterway', 'flow', 'current', 'freshet',
    'mountains', 'mountain', 'peak', 'summit', 'hill', 'ridge', 'mount', 'mountaineer', 'alpine', 'alps',
    'waterfalls', 'waterfall', 'cascade', 'falls', 'cataract', 'plunge', 'plunge', 'rapids', 'rapids', 'rapids',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback', 'backwoods', 'badlands', 'wilds',
    'scenic', 'view', 'vista', 'scene', 'landscape', 'panorama', 'horizon', 'scenery', 'outlook', 'lookout',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'stargazing', 'stars', 'starry', 'night', 'sky', 'universe', 'galaxy', 'cosmos', 'astronomy', 'constellation',
    'exploring', 'explore', 'venture', 'discovery', 'journey', 'journey', 'trip', 'adventure', 'quest', 'expedition',
    'adventures', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'campfires', 'campfire', 'fire', 'blaze', 'flame', 'burn', 'embers', 'cinders', 'heat', 'warmth',
    'barbecues', 'barbecue', 'grill', 'grilling', 'cookout', 'roast', 'cook', 'smoke', 'fire', 'food',
    'outdoor', 'external', 'exterior', 'open-air', 'outside', 'outdoorsy', 'alfresco', 'field', 'country', 'rural',
    'games', 'game', 'play', 'fun', 'pastime', 'activity', 'sport', 'competition', 'outdoor', 'playtime',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'exercise', 'workout', 'training', 'fitness', 'activity', 'physical', 'activity', 'aerobic', 'exercise', 'training',
    'gardening', 'garden', 'horticulture', 'cultivation', 'planting', 'plants', 'flowers', 'vegetables', 'fruit', 'herbs',
    'picnic', 'outdoor', 'lunch', 'meal', 'meal', 'food', 'lunch', 'outing', 'excursion', 'gathering', 'lunchtime',
    'walking', 'walk', 'hike', 'ramble', 'stroll', 'saunter', 'march', 'trek', 'tread', 'hiking',
    'running', 'run', 'race', 'sprint', 'dash', 'jog', 'marathon', 'running', 'runner', 'jogging',
    'bushwalking', 'walk', 'hike', 'trek', 'tramp', 'ramble', 'stroll', 'amble', 'march', 'hiking',
    'sightseeing', 'look', 'view', 'scene', 'scenery', 'sight', 'spectacle', 'landscape', 'panorama', 'outlook',
    'day trips', 'day', 'excursion', 'outing', 'trip', 'adventure', 'journey', 'journey', 'travel', 'tour',
    'parks', 'park', 'green', 'area', 'playground', 'recreation', 'ground', 'outdoor', 'space', 'commons',
    'beauty', 'beautiful', 'gorgeous', 'lovely', 'scenic', 'pretty', 'stunning', 'attractive', 'magnificent', 'splendid',
    'sunset', 'sunrise', 'sun', 'rise', 'dusk', 'dawn', 'twilight', 'evening', 'morning', 'daybreak',
    'sports', 'sport', 'athletics', 'exercise', 'physical', 'activity', 'recreation', 'leisure', 'pastime', 'pursuit',
    'fun', 'enjoyment', 'pleasure', 'entertainment', 'amusement', 'delight', 'joy', 'recreation', 'merriment', 'relaxation',
    'adventure', 'venture', 'expedition', 'quest', 'journey', 'journey', 'travel', 'trip', 'tour', 'expedition',
    'wildlife', 'animals', 'wild', 'creature', 'critter', 'fauna', 'wilds', 'nature', 'predator', 'prey',
    'wilderness', 'wild', 'jungle', 'desert', 'wasteland', 'bush', 'outback','gym','school']

export const outdoorKeywords = [...new Set(keywords)];

  