import StoreProvider from "@/redux/provider";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "To Do List App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-2 sm:px-8 py-4">
      <StoreProvider>
      <Navbar />
      {children}
      </StoreProvider>
      </body>
    </html>
  );
}
